### ISSUE TITLE
Anzeige Parallelgruppen und Termine: Reihenfolge und Überschriften

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-lectures#108]
> Wenn man auf https://www.ps.tf.fau.de/lehre/lehrveranstaltungen/#collapse_4 die Parallelgruppen der "echnerübungen zu Algorithmen und Datenstrukturen" anschaut, sieht man, dass zuerst die 3., dann die 8., dann die 2., ... Parallelgruppe angezeigt wird. Man wünscht sich eine sortierte Ausgabe.
<img width="1208" alt="grafik" src="https://github.com/RRZE-Webteam/rrze-lectures/assets/1070669/02cdb7a5-b821-4a0f-a45c-de11c26927c3">

> Wenn es wie bei der Vorlesung https://www.ps.tf.fau.de/ue2/  nur eine einzige Parallelgruppe gibt, dann ist die Überschrift "1. Parallelgruppe" verzichtbar.

<img width="1208" alt="grafik" src="https://github.com/RRZE-Webteam/rrze-lectures/assets/1070669/82a36136-3e85-461c-851f-1807b96b66b9">

**Comment by thenickless** [comment]
Notiz:

[lectures fauorgnr="1513001200,1513071400" type="Vorlesung, Übung, Hauptseminar, Seminar" format="tabs"]

**Comment by thenickless** [comment]
=> API sortiert nicht per default wie in Campo eingegeben - siehe:

https://api.fau.de/pub/v2/vz/educationEvents/?limit=100&lq=providerValues.event_orgunit.fauorg%5Bin%5D%3D1513001200%253B1513071400%26providerValues.courses.cancelled%3D0%26providerValues.courses.semester%3DSoSe2023%26providerValues.event.eventtypes%5Bin%5D%3DVorlesung%253B%25C3%259Cbung%253BHauptseminar%253BSeminar&lf=providerValues.courses.semester%3DSoSe2023&page=1

=>

**Comment by xwolfde** [comment]
Könnte man im Zweifel nicht selbst sortieren? Erstmal alle Daten über die API holen, cachen im Transient und danach zur Anzeige sortieren? Hätte den Vorteil, dass wir dann bei der ANzeige auch eine Sort- Option anbieten können, die dann beim Aufruf auf die Daten ims transient zurückgreift und dann nichtnochmal die API bemüht.

**Comment by thenickless** [comment]
Ja, das geschieht bereits an anderer Stelle (z.B. degree). Performanter ist jedoch, wenn das die API tut. Wir hatten bereits Performance-Probleme, die dazu geführt haben, dass wir die Anzahl an LV beschränken müssen, was Kunden bereits irritiert hat.

**Comment by thenickless** [comment]
> Könnte man im Zweifel nicht selbst sortieren? Erstmal alle Daten über die API holen, cachen im Transient und danach zur Anzeige sortieren? Hätte den Vorteil, dass wir dann bei der ANzeige auch eine Sort- Option anbieten können, die dann beim Aufruf auf die Daten ims transient zurückgreift und dann nichtnochmal die API bemüht.

=> ist nun im Plugin eingebaut, auch damit das Plugin stets stabil läuft, weil die API sich zZt zeitweise unterschiedlich verhält und zB gerade den LQ Parameter providerValues.courses.cancelled ignoriert, der vor 20h noch genutzt werden konnte.

**Comment by xwolfde** [comment]
Leben wir halt mit dem was wir kriegen und machen das Beste draus.
Dann haben wir auch die Kontrolle darüber, wie was gemacht wird
