### ISSUE TITLE
Installation with WP Pusher

### ISSUE THREAD

**Issue by merlzbert** [RRZE-Webteam/rrze-lectures#123]
Dear team,

in the past we have typically installed the RRZE plugins  (RRZE UnivIS, RRZE TOS, FAU Person, etc.) for our WP instance with WP Pusher. When trying to install rrze-lectures with WP Pusher we now face an error (An error occured: The package could not be installed.). Are you aware why this may be happening? Our alternative approach is of course to install the plugin manually - but this makes the maintenance for us harder, than when using with WP Pusher. I would appreciate any feedback, thanks!

Best regards

**Comment by xwolfde** [comment]
Could you look and add some details? We dont use WP Pusher.

Neither by our own git-updater (https://gitlab.rrze.fau.de/rrze-webteam/rrze-updater/-/tree/master) nor by direct github-request I get such error.

**Comment by xwolfde** [comment]
No answer, not really a matter of this plugin => issue closed
