### ISSUE TITLE
Dev: Kritischer Fehler wenn fauorg-nr fehlt

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-lectures#147]
Wenn in den Settings keine FAU-OrgNr. eingetragen ist und trotzdem ein [lectures] shortcode gesetzt wird, erhält der Nutzer einen kritischen Fehler:

![Bildschirmfoto 2023-09-15 um 14 06 32](https://github.com/RRZE-Webteam/rrze-lectures/assets/58593037/c0c2dace-ce9d-4322-83ec-0a7e08138de1)
s. https://www.beta.wordpress.rrze.fau.de/plugins/rrze-lectures/lectures-standardausgabe/

**Comment by xwolfde** [comment]
gefixt in 2.0.27
