### ISSUE TITLE
dem-Attribut gibt falsches Jahr aus?

### ISSUE THREAD

**Issue by lukasniebler** [RRZE-Webteam/rrze-lectures#150]
beim RRZE-Lectures Plugin ist folgendes Problem aufgetreten: Wenn ich unter Attribute 

[lectures format="tabs" lecturer_idm="idm-kennung" sem="WiSe2023"]
Beispiel des vollständigen Shortcodes s. Helpdesk 🎫 http://go.fau.de/9vrpf

eingebe, werden fälschlicherweise meine Veranstaltungen des Wintersemesters 22/23 (und nicht WS 23/24) angezeigt. Handelt es sich dabei evtl. um einen Bug?

**Comment by itodnerd** [comment]
Geht uns genauso.
Bei uns wird ohne sem attribut und mit sem="1" der selbe Inhalt ausgegeben.

https://www.cs6.tf.fau.de/lehre/lehrveranstaltungen/#collapse_11

Lehrveranstaltungen aus dem aktuellen Semester (sem nicht vorhanden)
Lehrveranstaltungen aus dem Kommenden Semester (sem="1")

Das hat vor dem Somersemester noch funktioniert.

**Comment by xwolfde** [comment]
Bugfix zum Bugfix war n oich notwendig und noch ein Gegentest. Ausserdem muss das Problem in #153 noch beheboben werden. Danach kommt es in den Main.
