### ISSUE TITLE
Durchführende einer Veranstaltung werden nicht mehr erkannt.

### ISSUE THREAD

**Issue by juuliamat** [RRZE-Webteam/rrze-lectures#153]
Es wurde gemeldet, dass das Plugin nur noch die Verantwortlichen einer Lehrveranstaltung erkennt,
nicht aber die Durchführenden, was folglich zu keiner Ausgabe führt. Siehe Beispiel: https://www.ps.tf.fau.de/mitarbeitende/mayer/#collapse_1 r. Mayer als Durchführender, nicht Verantwortlicher --> keine Ausgabe

**Comment by xwolfde** [comment]
Offenbar sind die Durchführenden nun in einen Subarray instructur.
Dort auch mit eine Reihenfolge versehen. Offenbar als Teil der API-Arbeiten um doe Sortorder der Durchführenden...

=> Die Suche nach lecturere muss geändert werden von lq auf rq mit 
`providerValues.courses.planned_dates.instructor.identifier=$ID[or]providerValues.courses.course_responsible.identifier=$ID`

**Comment by xwolfde** [comment]
Nach Klärung mit dem DIP-Team:

1. Die Suche funktioniert entsprechend der Definition. Es wurde bislang immer nur in providerValues.courses.course_responsible.identifier. Das in dem einen Sommersemester Veranstaltungen für die Person gefunden wurden, aber im Wintersemester nun nicht mehr. LIegt daran, dass die Person im Wintersemester nicht mehr in  providerValues.courses.course_responsible.identifier auftaucht.
2. Die OR-Suche kann leider so nicht funktionieren, da die Suche im RHS(right-hand-side) Schema nur innerhalb von gleichen Parametern, aber nicht von unterschiedlichen Parametern funktioniert. Zitat Dev:

>  Man kann momentan nicht (und ist soweit nicht vorgesehen) Attributen 'or'-en.
> Das 'or' bei 'rq' bezieht sich auf dem Wert(aus der Doku: "use [or] to or value criteria", "...birthdate=gte:1998-04-16T22:00:00Z[or]lte:1955-04-16T22:00:00Z ...").
> Das Wert ist auf dem rechten Seite nachedm '=' (deswegen heisst es 'rq')
> Anders gesagt, man sucht mit Vornamen = 'Woflgang' oder 'Krasimir', aber nicht mit Vorname 'Wofgang' oder Nachname 'Zhelev'.
> Die 'or' Expression von obe:
>  rq=[providerValues.courses](http://providervalues.courses/).course_responsible.identifier=96dd85a6a6[or][providerValues.courses](http://providervalues.courses/).planned_dates.instructor.identifier=96dd85a6a6
> wird deswegen so interpretiert:
>   [providerValues.courses](http://providervalues.courses/).course_responsible.identifier = '96dd85a6a6' 
>        oder 
>   [providerValues.courses](http://providervalues.courses/).course_responsible.identifier = '[providerValues.courses](http://providervalues.courses/).planned_dates.instructor.identifier=96dd85a6a6'
> Weil nach dem 'or' soll den anderen Wert kommen.
> 

Eine Lösung derart, dass man nun zwei Suchen in der API nacheinander durchführt und deren Ergebnisse mergt, wäre zwar denkbar auf aufwendig: Da man ja mehr als eine Person suchen kann, würden für jede in dem Suchfiltern augfeührte Person 2 Requests an die API gehen. Diese Requests würden aufgrund unterschiedlicher Laufzeiten zudem über ein await/fetch-Verfahren abgewartet werden müssen, was dann die Performance drücken würde.
Zwar kann man auch dies lösen, aber hier wäre dennoch die bisherige Funktion zum Abruf der Daten komplett umzuschreiben.


Mit dem DIP Team wurde mit Blick auf die vorhandenen Ressourcen diesem Weg eine Absage erteilt. 
Es ist daher stattdessen folgender simpler Workaround zu machen: Im Campo sind die Personen, die mit Lehrveranststulungen findbar sein sollen, auch in der Liste der responsible Personen einzutragen. Das Plugin wird, wie bisher schon, nur darin suchen.
