### ISSUE TITLE
Individuelle not-found-message hinzufügen. "Keine passenden Einträge gefunden."

### ISSUE THREAD

**Issue by pateck90** [RRZE-Webteam/rrze-lectures#157]
Leider wird beim Anlagen von neuen Lehrveranstaltungen, welche in diesem Semester nicht angeboten werden bei uns "Keine passenden Einträge gefunden." angezeigt. Kann man hier vielleicht nen flag in den shortcode hinzufügen, welcher diesen default-wert überschreibt?
Wir hätten gerne eine message mit etwas mehr Informationsgehalt wie "Diese Lehrveranstaltung wird in diesem Semester nicht angeboten". Ein Workaround wäre aktuell Lehrveranstaltungen vom letzten Semester zu nehmen. Das kann aber ja keine Lösung auf dauer sein und ist imho auch etwas verwirrend für die Studenten.

**Comment by xwolfde** [comment]
Verwenden Sie hierzu das Attribut
`   nodata=""`

Also zum Beispiel:
`   nodata="Diese Lehrveranstaltung wird in diesem Semester nicht angeboten"`
