### ISSUE TITLE
Anregung: Option für Semesterauswahl

### ISSUE THREAD

**Issue by deserno** [RRZE-Webteam/rrze-lectures#20]
Eine Option, um die Lehrveranstaltungen für ein bestimmtes Semester anzuzeigen, wäre praktisch. Äquivalent zum Parameter "sem=.." im UnivIS-Plugin.

**Comment by xwolfde** [comment]
Ist/war bereits vorgesehen, da Teil des vorherigen Plugins.

Zusammenhang auch zu #21

**Comment by thenickless** [comment]
Umgesetzt in 1.4.26
