### ISSUE TITLE
Sem-Parameter: Syntax Semesterangabe

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-lectures#25]
Im UnivIS-Plugin wird bei der Attribut sem="" die Syntax `YYYYs` und `YYYYw`   verwenden.

Bei der Abfrage der neuen zentralen API  mit dem Parameter `$$courses.semester` brauchen wir intern die Syntax `SoSeYYYY` und `WiSeYYYY`

Ich würde aber vorschlagen, dass  im Short-Attribut beide Formen, aber vielleicht auch zusätzlich als drittes die Formen `SSYYYY` und `WSYYYY` möglich sind. Einfach um zu verhindern, dass jemand bei Eingabe der alten Form dann nichts mehr bekommt. Die Form kann man ja gut erkennen und dann für die API-Anfrage umbauen, wenn nötig.

**Comment by thenickless** [comment]
in 1.4.23 umgesetzt
