### ISSUE TITLE
"teaching_language" funktioniert nicht

### ISSUE THREAD

**Issue by FlorianFiller** [RRZE-Webteam/rrze-lectures#51]
Trotz Filter teaching_language="en" werden Lehrveranstaltungen, die in campo "Lehrsprache: Deutsch" stehen haben, angezeigt/exportiert.

Relativ willkürlich gewähltes Beispiel:
![grafik](https://user-images.githubusercontent.com/12810141/223399745-7ba48374-2e48-4d81-809b-6a4ae99a5349.png)

![grafik](https://user-images.githubusercontent.com/12810141/223399964-08b5329c-e317-4dcd-ba9c-6c9043172992.png)

![grafik](https://user-images.githubusercontent.com/12810141/223400133-a9afb27f-0d52-442c-91c9-641ae77c14fa.png)

**Comment by thenickless** [comment]
Danke für den Hinweis. teaching_language ist in Entwicklung. Grund war, dass ich irrtümlich die Readme.md vom Dev auf den Main-Branch committed hatte. Bitte entnehmen Sie weitere Informationen der jetzt wieder aktuellen Readme.md : https://github.com/RRZE-Webteam/rrze-lectures#readme

**Comment by FlorianFiller** [comment]
Lieber Herr Klemencic,

vielen Dank – gelöst ist das Problem dadurch aber ja noch nicht.
Ich war nur darüber gestolpert, weil im Issue „Mehrsprachigkeit“ (https://github.com/RRZE-Webteam/rrze-lectures/issues/19) steht:
Stand 2023-02-24:

  *   API ist in Arbeit (Multilang-Felder werden Arrays liefern)
  *   display_language ist mit 1.6.7 vorbereitet
  *   teaching_language ist mit 1.6.8 umgesetzt
  *   Dokumentation muss um diese Info ergänzt werden, sobald API fertig ist & alles rund läuft:

Dann warten wir weiterhin ab und hoffen, dass es zum Sommersemester geht.

Viele Grüße
Florian Filler

- -
Florian Filler
Friedrich-Alexander-Universität Erlangen-Nürnberg
Philosophische Fakultät und Fachbereich Theologie
Hindenburgstraße 34
91054 Erlangen
Tel: +49 9131 85-23170
Mobil: +49 174 6271865
Fax: +49 9131 85-22176
***@***.******@***.***>
www.phil.fau.de<http://www.phil.fau.de/>

Von: Benjamin Klemencic ***@***.***>
Gesendet: Mittwoch, 8. März 2023 14:00
An: RRZE-Webteam/rrze-lectures ***@***.***>
Cc: Filler, Florian ***@***.***>; Author ***@***.***>
Betreff: Re: [RRZE-Webteam/rrze-lectures] "teaching_language" funktioniert nicht (Issue #51)


Danke für den Hinweis. teaching_language ist in Entwicklung. Grund war, dass ich irrtümlich die Readme.md vom Dev auf den Main-Branch committed hatte. Bitte entnehmen Sie weitere Informationen der jetzt wieder aktuellen Readme.md : https://github.com/RRZE-Webteam/rrze-lectures#readme

**Comment by thenickless** [comment]
Sehr geehrter Herr Filler,

"vielen Dank – gelöst ist das Problem dadurch aber ja noch nicht."

Das liegt in der Natur der Sache.

"Ich war nur darüber gestolpert, weil im Issue „Mehrsprachigkeit“ ([#19](https://github.com/RRZE-Webteam/rrze-lectures/issues/19)) steht:
Stand 2023-02-24:"
Ja, und darunter ein weiterer Kommentar: 
https://github.com/RRZE-Webteam/rrze-lectures/issues/19#issuecomment-1444053811

Bitte haben Sie Verständis dafür, dass ich meine (unsere) Entwickler-Kommentare und Informationen nicht kundengerecht halten kann. Wir sind ein sehr kleines Webteam mit der Prämisse, unseren Kunden die bestmöglichen Tools samt Support anzubieten, verfügen jedoch nicht über Kapazitäten, das während des Entwicklungsprozesses auch für Fachunkundige fehlerfrei zu dokumentieren. Ich schließe nun dieses Issue, um dieses Plugin rasch zu einem besseren Stand zu bringen. Der aktualisierten Readme.md können Sie entnehmen, dass mehrere Abteilungen und das mit unterschiedlicher Art an Klärungsbedarf daran beteiligt sind, weshalb die Entwicklung nicht -wie üblich- so abläuft, dass unsere Kunden keine Unstimmigkeiten bemerken. Ich bedauere diesen Zustand nicht ändern zu können. In Kürze jedoch wird es wieder ein Update des Plugins geben und es wird im weiteren Prozess viele weitere Updates geben, die möglichst reibungslos (mein Code berücksichtigt bereits bestimmte Struktur-Änderungen falls die Schnittstelle sich wieder ändern sollte. Die Schnittstelle programmiere nicht ich.

**Comment by FlorianFiller** [comment]
Lieber Herr Klemencic,

ich habe vollstes Verständnis dafür und versuche ja auch gerne mich in nicht „kundengerecht“ aufbereitete Inhalte einzudenken.
Mir ging es ja nur darum, zu signalisieren, dass die Möglichkeit, nach Lehrveranstaltungssprache zu filtern, für uns wichtig ist. Dass das ggf. länger dauert als uns allen lieb ist, ist (leider) ja keine Seltenheit.


Viele Grüße
Florian Filler

- -
Florian Filler
Friedrich-Alexander-Universität Erlangen-Nürnberg
Philosophische Fakultät und Fachbereich Theologie
Hindenburgstraße 34
91054 Erlangen
Tel: +49 9131 85-23170
Mobil: +49 174 6271865
Fax: +49 9131 85-22176
***@***.******@***.***>
www.phil.fau.de<http://www.phil.fau.de/>

Von: Benjamin Klemencic ***@***.***>
Gesendet: Mittwoch, 8. März 2023 14:19
An: RRZE-Webteam/rrze-lectures ***@***.***>
Cc: Filler, Florian ***@***.***>; Author ***@***.***>
Betreff: Re: [RRZE-Webteam/rrze-lectures] "teaching_language" funktioniert nicht (Issue #51)


Sehr geehrter Herr Filler,

"vielen Dank – gelöst ist das Problem dadurch aber ja noch nicht."

Das liegt in der Natur der Sache.

"Ich war nur darüber gestolpert, weil im Issue „Mehrsprachigkeit“ (#19<https://github.com/RRZE-Webteam/rrze-lectures/issues/19>) steht:
Stand 2023-02-24:"
Ja, und darunter ein weiterer Kommentar:
#19 (comment)<https://github.com/RRZE-Webteam/rrze-lectures/issues/19#issuecomment-1444053811>

Bitte haben Sie Verständis dafür, dass ich meine (unsere) Entwickler-Kommentare und Informationen nicht kundengerecht halten kann. Wir sind ein sehr kleines Webteam mit der Prämisse, unseren Kunden die bestmöglichen Tools samt Support anzubieten, verfügen jedoch nicht über Kapazitäten, das während des Entwicklungsprozesses auch für Fachunkundige fehlerfrei zu dokumentieren. Ich schließe nun dieses Issue, um dieses Plugin rasch zu einem besseren Stand zu bringen. Der aktualisierten Readme.md können Sie entnehmen, dass mehrere Abteilungen und das mit unterschiedlicher Art an Klärungsbedarf daran beteiligt sind, weshalb die Entwicklung nicht -wie üblich- so abläuft, dass unsere Kunden keine Unstimmigkeiten bemerken. Ich bedauere diesen Zustand nicht ändern zu können. In Kürze jedoch wird es wieder ein Update des Plugins geben und es wird im weiteren Prozess viele weitere Updates geben, die möglichst reibungslos (mein Code berücksichtigt bereits bestimmte Struktur-Änderungen falls die Schnittstelle sich wieder ändern sollte. Die Schnittstelle programmiere nicht ich.
