### ISSUE TITLE
Kunden-Vorschläge zur Verbesserung der Version 2

### ISSUE THREAD

**Issue by thenickless** [RRZE-Webteam/rrze-lectures#69]
_Ticket done_

**Comment by thenickless** [comment]
https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom&TicketID=1095779

**Comment by thenickless** [comment]
**Filterung nach Department**

"Will man z.B. die Veranstaltungen eines ganzen Departments auflisten,
reicht es nicht aus die OrgaNr des Departments einzutragen.

Es muss von jedem Lehrstuhl und vom jeder Professur, die LVs anbietet
(und die angezeigt werden sollen), die OrgaNummern (mit Komme getrennt)
eingetragen werden."

https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=1083494

**Comment by thenickless** [comment]
Kundenwunsch, nach Frühstudium zu filtern.

(wie es bei rrze-univis möglich war)

**Comment by thenickless** [comment]
Bedarf: "Filterung nach Frühstudium" (via Cathrin Gräf https://matrix.to/#/!lAQHJvCVCkyDRUiFGk:fau.de/$_iKA83hUaslPev59TBMWWDJeMU0mU3mdtwcNfskJT5o?via=fau.de )

Diese LV ist für Frühstudium geeignet:
"Kleines Geländeseminar 3-tägig"

Auf der Campo-Website ist diese Info nicht ersichtlich: https://www.campo.fau.de/qisserver/pages/startFlow.xhtml?_flowId=detailView-flow&_flowExecutionKey=e3s1

https://api.fau.de/pub/v1/vz/educationEvents/?limit=25&attrs=identifier%3Bname%3BproviderValues.event.eventtype%3BproviderValues.courses.url%3BproviderValues.courses.semester%3BproviderValues.event.title%3BproviderValues.event.shorttext%3BproviderValues.event_orgunit.orgunit%3BproviderValues.event.comment%3BproviderValues.courses.hours_per_week%3BproviderValues.courses.teaching_language%3BproviderValues.courses.course_responsible.prefixTitle%3BproviderValues.courses.course_responsible.firstname%3BproviderValues.courses.course_responsible.surname%3BproviderValues.courses.contents%3BproviderValues.courses.literature%3BproviderValues.courses.compulsory_requirement%3BproviderValues.courses.attendee_maximum%3BproviderValues.courses.attendee_minimum%3BproviderValues.courses.planned_dates.rhythm%3BproviderValues.courses.planned_dates.weekday%3BproviderValues.courses.planned_dates.starttime%3BproviderValues.courses.planned_dates.endtime%3BproviderValues.courses.planned_dates.individual_dates.cancelled%3BproviderValues.courses.planned_dates.individual_dates.date%3BproviderValues.courses.planned_dates.startdate%3BproviderValues.courses.planned_dates.enddate%3BproviderValues.courses.planned_dates.expected_attendees_count%3BproviderValues.courses.planned_dates.comment%3BproviderValues.courses.planned_dates.instructor.prefixTitle%3BproviderValues.courses.planned_dates.instructor.firstname%3BproviderValues.courses.planned_dates.instructor.surname%3BproviderValues.courses.planned_dates.famos_code%3BproviderValues.event.frequency%3BproviderValues.event.semester_hours_per_week%3BproviderValues.courses.parallelgroup%3BproviderValues.modules.module_cos.subject&lq=names%3DKleines+Gel%C3%A4ndeseminar+3-t%C3%A4gig%26providerValues.courses.semester%3DSoSe2023&lf=providerValues.courses.semester%3DSoSe2023&page=1

**Comment by thenickless** [comment]
**Sortierung nach Modulen**

"Für die Auswahl und Suche der zugehörigen Lehrveranstaltungen wäre es hilfreich, wenn wir also nicht nur nach Studiengang, sondern dann nach Modulen sortieren könnten, anstelle von Lehrveranstaltungsgattung."

https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom;TicketID=1095624

**Comment by thenickless** [comment]
**Filterung nach Durchführenden und nicht nur nach Verantwortlichen einer LV**

https://www.helpdesk.rrze.fau.de/otrs/index.pl?Action=AgentTicketZoom&TicketID=1100478

**Comment by thenickless** [comment]
Nützlich: API liefert Timestamp der Aktualisierung

**Comment by xwolfde** [comment]
Alles obnige in verschiedene Subissues gespalten:
- Campo-Links/Studon-Links: #106 
- Organisationseinheit: #107 
- Parallelgruppenreihenfolge: #108 
- Raumangaben: #109 
- Filterung nach Department: #110 
- Andere Suchformen als LVs und Dozenten: verschiedene Issues
- Modulsuche: #111 
- Filterung nach Durchführenden: #90 
- Timestampanzeige: #89 
- Suche nach Studiengang - erstmal aussen vor lassen, da Zusammenhang zu Mein Studium-Daten.
