### ISSUE TITLE
Einzelanzeige einer Veranstaltung nach Titelsuche funktioniert nicht

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-lectures#81]
Beispiel:

`[lectures lecturer_identifier="4857e491bb" format="tabs" lecture_name="Systemprogrammierung 1"]`

Dies sollte lt. Doku nur die Vorlesung "Systemprogrammierung 1" von Dr. KLeinöder zeigen.
Stattdessen werden alle zugeordnete Veranstaltungen gezeigt.

Der Versuch statt `lecture_name="Systemprogrammierung 1"` das Leerzeichen zu ändern auf die normale Slugsyntax  `lecture_name="Systemprogrammierung_1"` ändert daran leider nichts.

**Comment by xwolfde** [comment]
Anmerkung: War im Mai schonmal behoben worden. Ggf. im falschen Branch gefixt.. ?

**Comment by thenickless** [comment]
[lectures sem="SoSe2023" degree="Physical Geography: Climate & Environmental Sciences"] funktioniert mit Branch main => liefert die Masterseminare, Vorlesungen und Vorlesungen mit Übung. Lag vielleicht am Cache?

**Comment by thenickless** [comment]
[lectures lecturer_identifier="4857e491bb" format="tabs" lecture_name="Systemprogrammierung 1"] => Bug: filtert nicht nach lecture_name, sondern nur nach lecturer_identifier

**Comment by xwolfde** [comment]
Heute funktionierte 
[lectures sem="SoSe2023" degree="Physical Geography: Climate & Environmental Sciences"]
wieder nicht. Auch verschiedene andere Schreibweisen halfen nicht. Suche in Campo zeigte den Studiengang, aber in Name und Titel standen verschiedene EInträge.
Ich vermute stark, dass es an einer MIschung an dem echten Degree-Namen in Campo liegt (in dem auch noch vor dem Namen der Abschluss und dahinter eine runde Klammer mit PO steht). 

Einzige dauerhafte und sichere Lösung und darauf würde ich mich jetzt konzentrieren: Suche nach der HIS-Identifier und nicht mehr nach diesen manuell eingegebenen Texten. Am Ende hängt es an irgendeinen optisch nicht erkennbaren UTF-64 Zeichen im Namen.

**Comment by xwolfde** [comment]
LIegt an der FAU-ORG-Nummer. Die wird mit in den Filter genommen, weswegen die Veranstaltung nur von den EInrichtungen gefunden werden, die auch moit der FAU ORG matchen.
Problem wird  mit #144 gelöst
