### ISSUE TITLE
Gecancelte Parallelgruppen und LVs werden angezeigt

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-lectures#91]
> 1) bei den Parallelgruppen der Tafelübungen https://www.ps.tf.fau.de/lehre/lehrveranstaltungen/#collapse_8 finden nur der 3 der 7 in Campo erfassten Parallelgruppen tatsaechlich statt. Campo zeigt die anderen als "gestrichen" an; das [lectures]-Plugin zeigt aber alle Parallelgruppen an. (Noch schlimmer wird das dadurch, dass durch die fehlerhafte Sortierung (s.u. bei 3) die tatsaechlich stattfindenden Parallelgruppen zufaellig erst am Ende angezeigt werden.)

Lt. Rückmeldung von DIP wird das Attribut "cancelled" bereit gestellt. Dieses muss ausgewertet werden und diese Einträge also ignoriert werden.

**Comment by thenickless** [comment]
API ignoriert gerade den LQ-Parameter providerValues.courses.cancelled=0 (providerValues.courses.cancelled%3D0), darum sicherheitshalber in Shortcode.php eingebaut (Z. 356) 2.0.15
