### ISSUE TITLE
Suche nach FAUOrg funktioniert nicht mehr?

### ISSUE THREAD

**Issue by xwolfde** [RRZE-Webteam/rrze-lectures#94]
In der aktuellen 2.0.10 liefert die Suche nach der FAUOrg keine Ergebnisse mehr.

Getestet sowohl auf dem produktiven CMS mit Main-Branch als auch auf einer Testinstanz mit Dev.

**Comment by thenickless** [comment]
Notiz:

- https://api.fau.de/pub/v2/vz/organizations/?sort=name%3D1&attrs=disambiguatingDescription%3Bname&q=RRZE
- https://api.fau.de/pub/v2/vz/organizations/?sort=name&attrs=disambiguatingDescription%3Bname&q=RRZE
- https://api.fau.de/pub/v2/vz/organizations?q=RRZE
- ditto mit v1

liefert stets 500

["response"]=>
  array(2) {
    ["code"]=>
    int(500)
    ["message"]=>
    string(21) "Internal Server Error"
  }

**Comment by thenickless** [comment]
liefert mit unserem API-Key über die Doku-Website ebenfalls 500

https://api.fau.de/doc

Requests:
- https://api.fau.de/pub/v1/vz/organizations?q=RRZE
- https://api.fau.de/pub/v2/vz/organizations?q=RRZE
